# Generated by Django 5.0.2 on 2024-02-14 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_snack_description_alter_snack_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='name',
            new_name='snack_name',
        ),
    ]
