# Generated by Django 5.0.2 on 2024-02-14 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0003_rename_name_snack_snack_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='snack_name',
            new_name='name',
        ),
    ]
